// @depends components/LayersViewer.js
// @depends components/ContextMenu.js
// @depends js/G.js
// @depends js/utils/logger.js
// @depends js/lib/alerts.js
// @depends js/config.js
// @depends js/components/Analyzer.js
// @depends js/components/creator.js
// @depends js/components/guiManager.js
// @depends js/components/panelManager.js
// @depends js/components/colorManager.js
// @depends js/utils/GVector2f.js
// @depends js/utils/utils.js
// @depends js/components/menu.js
// @depends js/components/slider.js
// @depends js/components/chatViewer.js
// @depends js/components/contextMenu.js
// @depends js/components/fileManager.js
// @depends js/components/optionManager.js
// @depends js/components/input.js
// @depends js/components/canvasManager.js
// @depends js/utils/canvasHandler.js
// @depends js/components/contentManager.js
// @depends js/components/selectedObjects.js
// @depends js/components/layer.js
// @depends js/components/scene.js
// @depends js/components/eventManager.js
// @depends js/components/timeLine.js
// @depends js/components/ConnectionManager.js
// @depends js/components/projectManager.js
// @depends js/components/paintManager.js
// @depends js/listeners.js
// @depends js/main.js
// @depends js/objects/entity.js
// @depends js/components/creatorViewer.js
// @depends js/objects/text.js
// @depends js/objects/table.js
// @depends js/objects/class.js
// @depends js/objects/polygon.js
// @depends js/objects/join.js
// @depends js/objects/rect.js
// @depends js/objects/paint.js
// @depends js/objects/line.js
// @depends js/objects/arc.js
// @depends js/objects/area.js
// @depends js/objects/graph.js
// @depends js/objects/imageObject.js
// @depends js/objects/textArea.js
// @depends js/objects/arrow.js
// @depends js/utils/test.js
// @depends js/components/sharer.js
// @depends js/components/taskManager.js
// @depends js/components/formManager.js
